/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterIcons.ttf
///
///
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * MFG Labs, Copyright (C) 2012 by Daniel Bruce
///         Author:    MFG Labs
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.mfglabs.com/
///
import 'package:flutter/widgets.dart';

class MyFlutterIcons {
  MyFlutterIcons._();

  static const _kFontFam = 'MyFlutterIcons';

  static const IconData folder = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData folder_open =
      const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData file_download =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData file_upload =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData video = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData search = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData heart_empty =
      const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData star_empty =
      const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData videocam =
      const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData users = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData user_add =
      const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData mic_outline =
      const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData mic = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData location =
      const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData switch_icon =
      const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData spin6 = const IconData(0xe839, fontFamily: _kFontFam);
  static const IconData export_icon =
      const IconData(0xf081, fontFamily: _kFontFam);
  static const IconData toggle_on =
      const IconData(0xf205, fontFamily: _kFontFam);
}
